kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - cd cli
  - go get
  - go build
  - go clean -cache

- name: package
  image: ubuntu
  settings:
    debug: true
  commands:
  - cd cli
  - mkdir -p infisical_1.0-1/usr/bin
  - mv -v DEBIAN infisical_1.0-1
  - mv -v infisical-merge infisical_1.0-1/usr/bin/infisical
  - dpkg-deb --build infisical_1.0-1