kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - cd cli
  - go get
  - go build
  - go clean -modcache

- name: package
  image: ubuntu
  settings:
    debug: true
  commands:
  - cd cli
  - mkdir -p infisical_1.0-1/usr/bin
  - cp -r DEBIAN infisical_1.0-1
  - cp infisical-merge infisical_1.0-1/usr/bin/infisical
  - dpkg-deb --build infisical_1.0-1

trigger:
  branch:
  - drone-test